name: 'config-scheme'
version: 1.3.0
usage: 'Repeatable configuration scheme for Helm Charts'
description: 'This plugin provides a convenient way to manage a set of configuration scheme'
useTunnel: false
command: '$HELM_PLUGIN_DIR/scripts/run.sh'

hooks:
  install: '$HELM_PLUGIN_DIR/scripts/wrapper/run.cmd $HELM_PLUGIN_DIR/scripts/install.sh'
  update: '$HELM_PLUGIN_DIR/scripts/wrapper/run.cmd $HELM_PLUGIN_DIR/scripts/install.sh'

platformCommand:
  - os: windows
    command: 'cmd /c $HELM_PLUGIN_DIR/scripts/wrapper/sh.cmd $HELM_PLUGIN_DIR/scripts/run.sh'

downloaders:
  - command: 'scripts/run.sh downloader'
    protocols:
      - 'config'
