name: 'config-scheme'
version: '0.0.0'
usage: 'Repeatable configuration scheme for Helm Charts'
description: |-
  This plugin provides a convenient way to manage a set of configuration scheme
  And allow to use those defined scheme in your chart operations

useTunnel: false
command: '$HELM_PLUGIN_DIR/scripts/run.sh'
platformCommand:
  - os: windows
    command: 'cmd /c $HELM_PLUGIN_DIR/scripts/wrapper/sh.cmd $HELM_PLUGIN_DIR/scripts/run.sh'
downloaders:
  - command: '$HELM_PLUGIN_DIR/scripts/run.sh downloader'
    protocols:
      - 'config'
